services:
  app:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}" #API Server
      - "${TCP_PORT}:${TCP_PORT}" #TCP Server
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - TCP_PORT=${TCP_PORT}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - evide-network

  postgres:
    image: postgis/postgis:17-3.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - evide-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
networks:
  evide-network:
    driver: bridge
